"""
Enhanced perplexity calculator supporting multiple model architectures
"""

import torch
import re
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
)
from collections import OrderedDict


class AdvancedPPL:
    def __init__(self, device=None, model_id="gpt2"):
        # Auto-detect device if not specified
        if device is None:
            if torch.cuda.is_available():
                self.device = "cuda"
                print("CUDA is available. Using GPU.")
            else:
                self.device = "cpu"
                print("CUDA not available. Using CPU.")
        else:
            self.device = device

        self.model_id = model_id
        print(f"Loading model '{model_id}' on device: {self.device}")

        try:
            # Use Auto classes for broader model support
            self.tokenizer = AutoTokenizer.from_pretrained(model_id)
            self.model = AutoModelForCausalLM.from_pretrained(
                model_id,
                torch_dtype=torch.float16 if self.device == "cuda" else torch.float32,
                device_map="auto" if self.device == "cuda" else None
            )

            # Add padding token if it doesn't exist
            if self.tokenizer.pad_token is None:
                self.tokenizer.pad_token = self.tokenizer.eos_token

        except Exception as e:
            print(f"Error loading model: {e}")
            raise e

        # Handle different model configurations
        if hasattr(self.model.config, 'n_positions'):
            self.max_length = self.model.config.n_positions
        elif hasattr(self.model.config, 'max_position_embeddings'):
            self.max_length = self.model.config.max_position_embeddings
        else:
            self.max_length = 1024  # Default fallback

        self.stride = min(512, self.max_length // 4)

    def getResults(self, threshold):
        """
        Adjust thresholds based on model - different models may need different thresholds
        """
        # You might need to calibrate these thresholds for different models
        if "gpt2" in self.model_id.lower():
            # Original GPT-2 thresholds
            if threshold < 60:
                label = 0
                return "The Text is generated by AI.", label
            elif threshold < 80:
                label = 0
                return "The Text is most probably contain parts which are generated by AI.", label
            else:
                label = 1
                return "The Text is written by Human.", label
        else:
            # Adjusted thresholds for larger models (may need calibration)
            if threshold < 40:
                label = 0
                return "The Text is generated by AI.", label
            elif threshold < 60:
                label = 0
                return "The Text is most probably contain parts which are generated by AI.", label
            else:
                label = 1
                return "The Text is written by Human.", label

    def __call__(self, sentence):
        """
        Main detection function
        """
        results = OrderedDict()

        total_valid_char = re.findall("[a-zA-Z0-9]+", sentence)
        total_valid_char = sum([len(x) for x in total_valid_char])

        if total_valid_char < 100:
            return {
                "status": "Please input more text (min 100 characters)"}, "Please input more text (min 100 characters)"

        lines = re.split(r'(?<=[.?!][ \[\(])|(?<=\n)\s*', sentence)
        lines = list(filter(lambda x: (x is not None) and (len(x) > 0), lines))

        ppl = self.getPPL(sentence)
        print(f"Perplexity {ppl}")
        results["Perplexity"] = ppl

        offset = ""
        Perplexity_per_line = []
        for i, line in enumerate(lines):
            if re.search("[a-zA-Z0-9]+", line) == None:
                continue
            if len(offset) > 0:
                line = offset + line
                offset = ""
            # Clean-up line
            line = line.strip()
            if line.endswith("[") or line.endswith("("):
                offset = line[-1]
                line = line[:-1]

            if len(line.strip()) > 0:
                ppl = self.getPPL(line)
                Perplexity_per_line.append(ppl)

        if Perplexity_per_line:
            avg_ppl = sum(Perplexity_per_line) / len(Perplexity_per_line)
            max_ppl = max(Perplexity_per_line)
        else:
            avg_ppl = ppl
            max_ppl = ppl

        print(f"Perplexity per line {avg_ppl}")
        results["Perplexity per line"] = avg_ppl

        print(f"Burstiness {max_ppl}")
        results["Burstiness"] = max_ppl

        out, label = self.getResults(results["Perplexity per line"])
        results["label"] = label

        return results, out

    def getPPL(self, sentence):
        """
        Calculate perplexity with improved memory management
        """
        encodings = self.tokenizer(
            sentence,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_length
        )
        seq_len = encodings.input_ids.size(1)

        nlls = []
        prev_end_loc = 0

        for begin_loc in range(0, seq_len, self.stride):
            end_loc = min(begin_loc + self.max_length, seq_len)
            trg_len = end_loc - prev_end_loc
            input_ids = encodings.input_ids[:, begin_loc:end_loc].to(self.device)
            target_ids = input_ids.clone()
            target_ids[:, :-trg_len] = -100

            with torch.no_grad():
                outputs = self.model(input_ids, labels=target_ids)
                neg_log_likelihood = outputs.loss * trg_len

            nlls.append(neg_log_likelihood)
            prev_end_loc = end_loc

            if end_loc == seq_len:
                break

        ppl = int(torch.exp(torch.stack(nlls).sum() / end_loc))
        return ppl

# Example usage with different models
if __name__ == "__main__":
    # Examples of models you could use:

    # Larger GPT-2 models
    # model = AdvancedPPL(model_id="gpt2-large")

    # Microsoft DialoGPT
    # model = AdvancedPPL(model_id="microsoft/DialoGPT-large")

    # GPT-Neo models
    # model = AdvancedPPL(model_id="EleutherAI/gpt-neo-1.3B")
    # model = AdvancedPPL(model_id="EleutherAI/gpt-neo-2.7B")

    # Llama models (if you have access)
    # model = AdvancedPPL(model_id="meta-llama/Llama-2-7b-hf")

    # Default to GPT-2
    model = AdvancedPPL(model_id="gpt2-large")

    test_text = """ 

    Soil health plays a critical role in sustaining agriculture, ensuring food security, and safeguarding environmental resources. It is the foundation upon which agricultural productivity, ecosystem resilience, and long-term economic stability depend. Healthy soils support plant growth, regulate water cycles, store carbon, and provide essential nutrients—all of which are vital for feeding a growing global population. However, across the European Union (EU), decades of intensive agricultural practices, including overuse of chemical fertilizers, monoculture cropping, and poor land management, have led to alarming rates of soil degradation. Erosion, loss of organic matter, compaction, salinization, and contamination are now common issues impacting millions of hectares of farmland. This degradation has not only undermined the productive capacity of agricultural land but has also imposed significant economic costs on farmers, governments, and society at large. Reduced yields, increased need for chemical inputs, and restoration expenses translate into lower farm income and rising food prices. Furthermore, soil degradation contributes to broader environmental problems such as water pollution, loss of biodiversity, and greenhouse gas emissions. In response to these challenges, the European Union has introduced a variety of soil protection policies and economic instruments as part of its broader environmental and agricultural strategies. Prominent among these are measures within the Common Agricultural Policy (CAP), including agri-environmental schemes, direct payments for organic farming, and targeted subsidies for soil restoration activities. These initiatives aim not only to mitigate the damage already done but also to incentivize sustainable land management practices that can prevent further degradation. This research explores these policy tools through an economic lens, assessing their effectiveness in improving soil health while supporting the financial viability of farmers. The study seeks to understand how these incentives influence decision-making in agriculture, promote long-term investment in land quality, and align with EU objectives such as climate resilience and the transition to a green economy. Special attention is given to their relevance for various stakeholders—including smallholder farmers, agricultural institutions, and policy-makers—highlighting both achievements and areas in need of further improvement. By evaluating existing programs and identifying best practices, the paper aims to contribute meaningful insights into how economic instruments can be optimized to safeguard one of the most vital natural resources: soil. In Europe from 2012 to 2020, the amount of land used for organic farming in the European Union increased by more than 50%, indicating a commendable growth rate of 5.7% every year1. By 2020, about 9.1% of all farmland in the EU was used for organic farming [Ibid]. Globally, in 2020, organic farming covered 74.9 million hectares, including lands that were in the process of transitioning to organic. Within the EU, organic farmland made up 14.8 million hectares, which is 19.7% of the world total and 9.1% of all EU agriculture [Ibid]. This expansion suggests a positive shift towards more sustainable agricultural practices. LITERATURE REVIEW A growing body of literature underlines the critical link between agricultural subsidies and soil conservation outcomes, highlighting the importance of well-structured policy instruments in promoting sustainable land use practices. At the core of this relationship are agri-environmental schemes (AES) and the Common Agricultural Policy (CAP) of the European Union, which provide financial incentives to farmers who adopt environmentally friendly practices. These schemes are designed not only to reduce the environmental impact of intensive farming but also to foster soil protection, biodiversity preservation, and water quality improvement. Reports by institutions such as the European Commission, the Organisation for Economic Co-operation and Development (OECD), and numerous peer-reviewed academic studies have emphasized the effectiveness of such economic instruments in driving behavioral change among farmers. Agri-environmental schemes, for instance, provide payments to landowners who implement practices like reduced tillage, crop rotation, organic farming, and maintenance of buffer strips. These practices are shown to significantly improve soil structure, increase organic matter content, and reduce erosion, contributing to the overall health of agricultural ecosystems. The CAP, through its Pillar II (Rural Development Program), further supports soil conservation by encouraging the adoption of organic farming methods. Direct payments under this pillar often include conditions tied to environmental performance, creating a dual incentive for both economic viability and ecological stewardship. Evidence from the literature indicates that farmers are more likely to engage in soil-preserving activities when financial compensation offsets the costs and risks associated with transitioning to sustainable methods. Several case studies strengthen the argument for the effectiveness of these policies. In Germany, for example, targeted subsidies for cover cropping and organic farming have led to measurable improvements in soil fertility and water retention capacity. In France, the implementation of regional AES programs has reduced pesticide usage and soil erosion in wine-producing regions. Italy has also seen success, particularly in areas like Tuscany and Emilia-Romagna, where farmers participating in CAP-funded organic farming schemes have reported both environmental and economic benefits, such as improved yields and income stability. Moreover, the literature points out that preventive soil protection measures are far more cost-effective than remedial interventions. Restoring degraded soils often requires significant financial investment and lengthy recovery periods, whereas maintaining soil health through proactive management is relatively inexpensive and yields long-term benefits. This has led policy experts to advocate for the redesign of subsidy frameworks to emphasize preventive approaches and performance-based incentives. In summary, the literature provides strong evidence that economic incentives, when properly designed and implemented, can effectively promote soil conservation in agriculture. The success of such policies depends on several factors, including the size of the payments, the clarity of environmental objectives, farmer awareness and education, and the administrative simplicity of the programs. Continued research and monitoring are essential to refine these instruments, ensuring that they not only protect vital soil resources but also enhance the resilience and profitability of the agricultural sector in the European Union. PROBLEM DESCRIPTION The fundamental problem at the heart of this research is the economic inefficiency caused by soil degradation, largely resulting from the continued reliance on conventional farming practices across the European Union. Intensive agricultural activities—such as monocropping, excessive use of chemical fertilizers, and over-tillage have contributed to the depletion of essential soil nutrients, loss of organic matter, erosion, and reduced water retention capacity. These processes not only diminish the long-term productivity of farmland but also impose significant costs on farmers, governments, and society at large. Economically, degraded soils lead to declining crop yields, higher dependency on agrochemical inputs, and increased restoration costs. In many cases, the productivity losses are compounded by environmental externalities such as water pollution, loss of biodiversity, and elevated greenhouse gas emissions. These inefficiencies affect both private and public interests, creating a strong rationale for policy intervention. In recognition of these challenges, the European Union has implemented various soil protection policies aimed at encouraging sustainable agricultural practices. These include financial incentives under the Common Agricultural Policy (CAP), agri-environmental schemes (AES), and targeted support for organic farming and soil restoration. However, despite the availability of such measures, their adoption and overall economic effectiveness vary significantly across Member States and regions. This disparity highlights a core concern: while some areas have made notable progress in soil conservation and sustainable land use, others continue to lag behind due to institutional, economic, or awareness-related barriers. Therefore, this study aims to investigate how soil protection policies and incentive structures can be optimized to achieve broader and more equitable outcomes in soil health restoration and agricultural sustainability. The analysis will focus on the interplay between policy design, economic impact, and adoption behavior, providing insights that can inform future policy development across the EU. ECONOMIC ANALYSIS Economic analysis plays a crucial role in understanding the effectiveness and impact of soil protection policies in agriculture, particularly within the context of the European Union. Soil degradation imposes high direct and indirect costs on farmers, including reduced yields, increased use of fertilizers and water, and loss of long-term land productivity. From a macroeconomic perspective, these inefficiencies translate into higher food prices, increased public spending on environmental restoration, and reduced competitiveness in the agricultural sector. One of the primary tools used to address these issues is the provision of economic incentives, such as subsidies and payments under the Common Agricultural Policy (CAP). These subsidies are designed to promote practices like organic farming, crop rotation, cover cropping, and the creation of buffer zones—all aimed at maintaining or improving soil quality. By shifting the cost-benefit calculus in favor of sustainable practices, such incentives aim to encourage farmers to internalize the positive externalities of soil conservation. Data from the European Commission suggests that countries with well-structured agri-environmental schemes (AES) and effective CAP implementation—such as Germany and France—have witnessed not only environmental improvements but also better economic returns in agriculture. For instance, farmers transitioning to organic practices have reported an average 10–20% increase in net income due to premium pricing and reduced input costs. Similarly, soil conservation practices have led to long-term savings by minimizing the need for synthetic fertilizers and irrigation. However, the uptake of such incentives is not uniform across all EU Member States. In regions with limited institutional support or awareness, farmers are less likely to adopt these practices, leading to uneven economic benefits. Moreover, the administrative complexity and delayed disbursement of subsidies can discourage participation. Cost-benefit analyses conducted by the OECD show that preventive soil protection measures yield a return on investment (ROI) ranging between 1.5 to 3.5 times the cost, depending on the scale and type of intervention. This reinforces the argument that investing in soil health is economically sound, not only for individual farmers but also for governments aiming to achieve sustainable development goals. CONCLUSIONS The evaluation of soil protection policies and economic incentives within the European Union reveals a clear trajectory toward sustainable agricultural practices, with a particular emphasis on organic farming and soil restoration. These efforts, primarily supported by the Common Agricultural Policy (CAP) and agri-environmental schemes, have demonstrated measurable success in reducing soil degradation, improving crop yields, and enhancing the economic resilience of farmers. The provision of financial subsidies has been instrumental in driving this transformation, especially in Member States with well-structured administrative systems and effective support mechanisms. Despite these achievements, significant challenges continue to limit the full realization of policy objectives. Among the most critical barriers are the lack of awareness and technical knowledge among farmers regarding sustainable practices, disparities in soil quality and farming systems across regions, and bureaucratic hurdles in accessing financial incentives. These issues contribute to uneven adoption rates and hinder the long-term impact of policy interventions. To address these limitations, the conclusion of this analysis calls for a refinement of existing policies. A shift toward performance-based incentive structures where financial support is directly tied to measurable environmental and economic outcomes could enhance policy efficiency and accountability. Additionally, investment in education, training, and advisory services for farmers is essential to build the capacity needed for sustainable soil management. Enhanced monitoring and evaluation frameworks are also recommended to track progress, identify best practices, and ensure that public funds are delivering the intended benefits. Tailoring policies to regional conditions and farmer profiles will further improve their relevance and effectiveness. By aligning economic incentives with long-term sustainability goals, the EU can foster a more inclusive, resilient, and environmentally sound agricultural sector. While the EU has made significant strides in promoting soil conservation and organic agriculture, continued adaptation and strategic investment are necessary to overcome persistent barriers and maximize the benefits of these initiatives. A balanced approach that combines financial support, education, and accountability will be key to securing the future of European agriculture and protecting its vital soil resources.

"""

    results, output = model(test_text)
    print("\nResults:", results)
    print("Output:", output)
